export const WorldStocklist = [
  "Australia (ASX)",
  "Canada (TSX, TSXV, CSE, NEO)",
  "Chile (BCS)",
  "China (SSE)",
  "Colombia (BVC)",
  "Cyprus (CSECY)",
  "Denmark (OMXCOP)",
  "Egypt (EGX)",
  "Estonia (OMXTSE)",
  "Finland (OMXHEX)",
  "Germany (FWB, SWB, XETR, BER, DUS, HAM, HAN, MUN, TRADEGATE)",
  "Hungary (BET)",
  "Iceland (OMXICE)",
  "India (BSE)",
  "Indonesia (IDX)",
  "Israel (TASE)",
  "Italy (MIL)",
  "Kuwait (KSE)",
  "Latvia (OMXRSE)",
  "Lithuania (OMXVSE)",
  "Poland (GPW, NEWCONNECT)",
  "Qatar (QSE)",
  "South Africa (JSE)",
  "South Korea (KRX)",
  "Switzerland (SIX, BX)",
  "Taiwan (TPEX)",
  "Turkey (BIST)",
  "UAE (ADX)",
  "United Kingdom (LSE, LSIN)",
  "Vietnam (HNX, UPCOM)",
];
